# Site settings
title: Samuel Sampaio
email: samuel@smk.net.br
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samuka.io" # the base hostname & protocol for your site
twitter_username: samukasmk
github_username:  samukasmk

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-97908701-1

gems:
  - jekyll-redirect-from
